os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip

jobs:
  include:
    - stage: "Tests" # naming the Tests stage
      name: "Unit Tests" # names the first Tests stage job
      script:
      - echo "Unit Tests"
    - stage: "Integration Tests"
      name: "Integration Tests" # names the second Tests stage job
      script:
      - echo "Unit Tests"
    - stage: deploy
      name: "Deploy Test"
      script:
      - echo "Deploy"

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
