os: linux
language: java
services:
  - docker
cashe: bundler
dist: bionic
install: skip

jobs:
  include:
    - name: "Java 8 Build"
      jdk: openjdk8
      script:
        - echo "Running build with Java 8"
        - true

    - name: "Java 11 Build"
      jdk: openjdk11
      script:
        - echo "Running build with Java 11"
        - true

    - name: "Java 17 Build"
      jdk: openjdk17
      script:
        - echo "Running build with Java 17"
        - true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
